### ISSUE TITLE
Unused parameter, and 'var' keywords

### ISSUE THREAD

**Issue by GerkinDev** [Shadowstep33/Angular2Pixi#10]
https://github.com/Shadowstep33/Angular2Pixi/blob/47e04aa96aac3803420d1189a903a3dfd597a8ef/src/providers/pixi.service.ts#L41

Some little problems like that are present in the codebase. Not blaming in any way, but should be fixed. Working on it already

**Comment by Shadowstep33** [comment]
Oh, yes *completely* understand. I try to separate emotions from code, so feel free to be as critical as possible moving forward. It's all towards improvement!
