### ISSUE TITLE
@NgModule Annotation for AoT

### ISSUE THREAD

**Issue by ArthurianX** [Shadowstep33/Angular2Pixi#16]
Hi, I'm just playing around with your module, looks good!, I have a problem when trying to do a AoT build with your module included.

```
ERROR in : Unexpected value 'PixiModule in /Users/MYAPP/node_modules/angular2pixi/dist/types/index.d.ts' imported by the module 'AppModule in /Users/MYAPP/src/app/app.module.ts'. Please add a @NgModule annotation.

```

I think it's really important to specify explicitly the barrel file, in order to have metadata set correctly.

Have a great day,
Arthur

**Comment by Shadowstep33** [comment]
Hi, glad you like it so far. Thanks, I'll take a look at this, this may relate to another problem we were having with compiling. 

I can't get to this immediately but I'll try to pop it in there on the next patch.

**Comment by GerkinDev** [comment]
Hey there!

Same issue here, with 0.3.6...
It may be useful if you add an `example` directory in your repo, so I'll check if I did something in a different way than yours.

**Comment by Shadowstep33** [comment]
Hm, so I actually tried adding NgModule to the index.d.ts file and it didn't seem to like that. I'll have to experiment. I have not actually compiled with aot yet as I'm unfamiliar with it and I'm still catching up to the latest angular philosophy lol

**Comment by Shadowstep33** [comment]
For the foreseeable future, AoT will not be supported. Please refer to https://github.com/Shadowstep33/Angular2Pixi/pull/12
