### ISSUE TITLE
Docs/Demo update?

### ISSUE THREAD

**Issue by GerkinDev** [Shadowstep33/Angular2Pixi#20]
Hi guy! Hope you are doing well!

I see that you did a lot of work on your module, I'm glad to see that :) But the doc is rather incomplete for now.. Could you improve it, or add a simple example app with the 0.4.x structure? I've been using the `renderer` & `scene` components that just disapeared, so my app does not want to compile anymore.

Any help appreciated, cheers!

**Comment by Shadowstep33** [comment]
Hey! So the bulk of the changes to old structure should be covered but I
have yet to document the new features (such as menu component). I will be
doing it piecemeal as my schedule is a bit hectic rn :(( I will try to
include a repo of some reproducable and minimal examples as well

Is that what you mean by incomplete?

**Comment by GerkinDev** [comment]
Yep, it would be great! I saw too late that my question was kinda duplicate with #18 , sorry about that

**Comment by Shadowstep33** [comment]
So, I am currently using a2p in one of my apps thats in closed testing
(I'll be sure to post it when its in open testing ;] ) BUT I dont use the
prod flag. Just release. There is still a problem with AoT - from what I
can tell it has to do with extending components. Thusly the move away from
Scene and Renderer and extending them. TextSprite still extends Sprite
component, so its possible once it no longer extends it AoT will work but
in the mean time, I suggest compiling with AoT disabled as a2p is not
compatible with it yet :((

**Comment by nphias** [comment]
Hi Shadowstep33!  so from the wiki home instuctions I could not get the pixiService to work.. below is the code that did work, please advice if the usage of the framework is correct / what you expected:
1. in my viewer module I import the PixiModule.
2. code for parent component.ts:

```javascript
import { Component, OnInit, Input, HostListener, ViewChild, ElementRef} from '@angular/core';
import { PixiService } from "angular2pixi";

@Component({
  selector: 'viewer',
  templateUrl: './viewer.component.html',
  styleUrls: ['./viewer.component.css']
})
export class ViewerComponent implements OnInit {
  @ViewChild("canvas") public canvas: ElementRef;
  canvasEl: HTMLCanvasElement
 @Input() infoPanelWidth:number
  arg1: number;
  arg2: number; 

  constructor(private pixiservice: PixiService) {
  }

  ngOnInit() {
    this.availableWidth = window.innerWidth - this.infoPanelWidth
    this.availableHeight = window.innerHeight
    const canvasEl: HTMLCanvasElement = this.canvas.nativeElement;
    this.pixiservice.init(this.availableWidth, this.availableHeight, canvasEl)
 }
```

3. code for parent component.html:

```
</div>
      <canvas #canvas>
	  <myview
		[argument1]="arg1"
		[argument2]="arg2">
        </myview>
      </canvas>
</div>
```
4. code from the child component:

```javascript
import {Component, Input, OnInit, SimpleChange} from '@angular/core';
import { PixiService } from "angular2pixi";

@Component({
  selector: 'myview',
  templateUrl: './myview.component.html',
  styleUrls: ['./myview.component.css']
})
export class MyviewComponent implements OnInit {

  @Input() argument1:number
  @Input() argument2:number
  mainStage: PIXI.Container = new PIXI.Container();

  layers = {
      background: new PIXI.Container(),
      hud: new PIXI.Container(),
      extras: new PIXI.Container()
  };

  constructor(private pixiservice: PixiService) {  }

  ngOnInit(){
      //add sprites etc to layers
      for (const l in this.layers) {
          this.mainStage.addChild(this.layers[l]);
      }
      this.pixiservice.worldStage.addChild(this.mainStage);
  }
```
as GerkinDev said .. you should really have a clearer example in the wiki.. thanks!

**Comment by Shadowstep33** [comment]
@nphias the proble with your example is you have two PixiService objects, so the worldStage you are adding the mainStage to in the child component is 

a.) never initialized
b.) never rendered

To solve that problem, what I generally end up doing is passing the reference down to components. For example, in my game I have a single gameService instance that gets passed down and looks as such:

```
GameService{
PixiService,
AuthService,
MenuService
...
}
```

So I just pass the game object down and everything has access to all needed supporting services (such as PixiService). Not 100% sure if this is the right or wrong way to do it... It's just how I'm doing it rn :S

I am currently working on a repo with examples. I will push it momentarily with a minimal use case just to help get y'all started.

**Comment by Shadowstep33** [comment]
@GerkinDev @nphias Please check out these links and let me know if they provide more sufficient examples and information:

https://github.com/Shadowstep33/Angular2Pixi/wiki/Example
https://github.com/Shadowstep33/a2p-demos

**Comment by Shadowstep33** [comment]
Please note the current version is v0.5.0 as I had some changes I really wanted to push to hopefully help the --prod issue and take care of some more simplification. Most notably, text-sprite no longer exists but sprite should be able to replace it. 

Not going to make a migration guide for these early builds but it will definitely be in the cards for later, more stable builds.

**Comment by nphias** [comment]
sure thats true (unless pixiservice is a singleton via providers )..well i like your example code.. i will try that .. it should be fine if never in your application design a child component needs to access methods on the pixiService.... resize is one method i need to use but i can do that from the parent by via the @HostListener("window:resize") event

**Comment by Shadowstep33** [comment]
@nphias Actually, my child components do access the member variables and methods of the PixiService. Here is an example of how (and why) in pseudo-code:

```

ChildComponent {
   @Input() game: any;
   
    this.h = this.game.scene.pixi.renderer.height;
    this.w = this.game.scene.pixi.renderer.width;
}
```

GameService has a dependency injected of SceneService and SceneService has PixiService. So basically for my game, GameService is kind of like an octopus that blesses every child component that receives it as an input with its tentacles. 

So they all require GameService to be passed down.

I would caution against using a2p's resize; it's not really working well at all. Making your own custom HostListener is the best bet right now; fixing resizing on the a2p level is in the roadmap but to an extent, it will either be minimal or just a pluggable listener and up to the developer to resize as desired. For example, will a general renderer resize always be viable or will some apps require some assets scale and others stay the same but re-position? It's slightly tricky.

**Comment by Shadowstep33** [comment]
@nphias @GerkinDev forgot to mention, if you're on Android you can actually check out a working example of a game using a2p developed by us 

https://play.google.com/store/apps/details?id=com.rabbitholegames.dayjob&hl=en_US
