### ISSUE TITLE
Can't build for production

### ISSUE THREAD

**Issue by GerkinDev** [Shadowstep33/Angular2Pixi#21]
SO! It's me again!

I've managed to get something working! But I still can't build it in `prod` env, using `ng build --prod`:

```
ERROR in : Unexpected value 'PixiModule in .../app/node_modules/angular2pixi/dist/types/pixi.module.d.ts' imported by the module 'AppModule in .../app/app.module.ts'. Please add a @NgModule annotation.
```

Here is a sample of my `app.module.ts`:
```typescript
import { NgModule } from '@angular/core';

import { BrowserModule } from '@angular/platform-browser';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { PixiModule } from 'angular2pixi';
import { routing } from './app.routes';

@NgModule({
	declarations: [
        /* ... */
	],
	imports: [
		BrowserModule,
		HttpClientModule,
        /* ... */
		routing,
		PixiModule,
	],
    /* ... */
})
export class AppModule {}
```

And here is my `tsconfig.json`

```json
{
	"compilerOptions": {
		"outDir": "./dist/out-tsc",
		"sourceMap": true,
		"declaration": false,
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"noImplicitAny": true,
		"strict": true,
        "skipLibCheck": true,
		"target": "es6",
		"typeRoots": [
			"node_modules/@types"
		],
		"types": [ "node" ],
		"lib": [
			"es2017",
			"dom"
		],
		"watch": true
	},
	"compileOnSave": false,
	"angularCompilerOptions": {
		"strictMetadataEmit" : true
    }
}
```

Well, that's at least much better than before 😄 but do you know how to finally build my app?

**Comment by Shadowstep33** [comment]
See my answer in your other issue but in short - dont use the prod flag :P

**Comment by Shadowstep33** [comment]
I would also experiment with emitDecorators as false; you may be able to
coerce prod mode to be more lenient with a2p as a module

**Comment by timwickey** [comment]
I have the same error:
ERROR in : Unexpected value 'PixiModule in .../node_modules/angular2pixi/dist/types/pixi.module.d.ts' imported by the module 'AppModule in .../src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by Shadowstep33** [comment]
@GerkinDev Let me know if v0.5.0 has any effect on this one; I don't have much experience building with just angular (generally I use Ionic for hybrid apps) and in a2p-demos I am getting a different error when trying to build using the prod flag

**Comment by Shadowstep33** [comment]
Thanks for closing this @GerkinDev
