### ISSUE TITLE
Error on PixiModule

### ISSUE THREAD

**Issue by devlfm** [Shadowstep33/Angular2Pixi#5]
Hi,

I imported your module on a test project like:
Import { PixiModule } from 'angular2pixi';

and I get this error:
>ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference
 to an exported function, resolving symbol NgModule

Can you help?

**Comment by Shadowstep33** [comment]
Hi, so I'm not at my personal computer but I may be able to posit some guesses. Are you using es5 or es6? I'm fairly certain emit decorators only works on with es6 (which A2P is using) so I'd try switching your project to es6 and see if that has any effect

**Comment by devlfm** [comment]
Hi, switching to es6 didn't worked either :(

**Comment by Shadowstep33** [comment]
Did the error change when you switched?

Can you post your tsconfig for your app?

This is my working one for reference:

```{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es6"
    ],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}```

**Comment by Shadowstep33** [comment]
Also, what version of angular, npm, and node are you using?

**Comment by Shadowstep33** [comment]
This thread here is seeming somewhat relevant https://github.com/angular/angular-cli/issues/3707

**Comment by Shadowstep33** [comment]
Closing this for lack of response, feel free to open if you have more info/have any luck or more questions
