### ISSUE TITLE
unexpected token in index.ts  

### ISSUE THREAD

**Issue by nphias** [Shadowstep33/Angular2Pixi#6]
I imported the pixi module
I get this error when trying run the module.. on the line that says 
export * from './pixi.module';     in index.ts

angular version: 4.4.6  (was unable and reluctant to downgrade to 4.1.3)
npm : 5.5.1
node: 8.6
typescript 2.5.3
electron 1.78

**Comment by nphias** [comment]
ok .. after some research i understand that typescript is set by default to not exclude directories under node_modules thats why it did not understand the keyword "export" .. so in the package.json file of the module I changed the main from "main": "./index.ts" to  "main": "./index.js".

it runs however the module import cannot be found in my app module 
/Users/angular/myproject/node_modules/@angular/compiler…:1550 Uncaught Error: Unexpected value 'PixiModule' imported by the module 'ViewerModule'. Please add a @NgModule annotation.

in the ViewerModule.ts  I have 
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { PixiModule } from 'angular2pixi/pixi.module';

seems it cannot find the PixiModule export reference in the angular bundle

**Comment by Shadowstep33** [comment]
You are importing from the module, you should import from the package. 

i.e:

```import { PixiModule } from 'angular2pixi';```

Let me know if that does or doesn't help

**Comment by Shadowstep33** [comment]
As a more thorough example:

```
import { 
	PixiModule,
	AssetService, 
	PixiService,
	SceneService 
} from 'angular2pixi';



@NgModule({
  declarations: [
...
  ],
  imports: [
...
	PixiModule,
...
  ],
  bootstrap: [],
  entryComponents: [
  ],
  providers: [
...
  ]
})
export class AppModule {}


```

**Comment by nphias** [comment]
Hi Shadowstep33,  thanks for your reply.. I find this package to be a really good idea in helping people to start using pixi and angular fast.. so respectfully  thank you for angular2pixi.

However I tried importing from the package:
import { PixiModule } from 'angular2pixi';
same error.. I was looking at other node_module packages with typescript typings that actually work for me like primeng.. will keep trying to fix it

**Comment by Shadowstep33** [comment]
I'm a bit confused by your project structure. The error is happening in `/Users/angular/myproject/node_modules/…` ? Did you install angular2pixi in the directory where it is being called, or as a sibling in `/Users/angular/myproject/node_modules`?

**Comment by Shadowstep33** [comment]
Also, for reference this is my applications tsconfig:


```{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es6"
    ],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "baseUrl": "."
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}```

**Comment by Shadowstep33** [comment]
@nphias I am closing this as it seems your app now runs

**Comment by nphias** [comment]
This needs to be re-opened .. it still doesnt work... the NPM package needs to be formatted in a way that works universally ( i tried changing my root level tsconfig file with the attributes above .. no luck. ) ... i will look at how to get the NPM package working from other typescript NPM package modules

**Comment by Shadowstep33** [comment]
I'll try creating a new angular 2 module from scratch (are you using Ionic?) and see what's going on. I'm thinking it's a config issue as when first installing that was what was tripping me up (primarily es5 vs es6 and experimentalDecorators).

**Comment by Jeff-Clark-MST** [comment]
I'm also encountering this issue when trying ng build. 

_Module build failed: Error: .........node_modules\angular2pixi\index.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property._

Adding the index.ts file manually into tsconfig gave another error: _ERROR in Error: No NgModule metadata found for 'AppModule'._

Like the idea of this package but need some help to get it working in my projcet

**Comment by Shadowstep33** [comment]
@Jeff-Clark-MST @nphias 

apologies for the delay, my day job hasn't given me much respite to work on this. I am beginning a new project to test angular2pixi and believe I have figured some stuff out about where the problem lies. Will work on making it more universal as @nphias has suggested.

**Comment by Shadowstep33** [comment]
@nphias I would suggest you upgrade all of your angular deps to 5.2.x

feel free to re-open this if the library breaks your project. I now have it successfully running in my projects. If it still isn't working for you, hopefully the PR from @GerkinDev will help fix things when we finish it
