### ISSUE TITLE
the browser does not support webgl - electron (chrome) - mac OS

### ISSUE THREAD

**Issue by nphias** [Shadowstep33/Angular2Pixi#7]
unable to get the package working from node_modules ... i put the pixi.module and related components, directives into my src directory where it works fine with the example code,  except that i now get this error
**_Error: This browser does not support webGL. Try using the canvas renderer_** 

stacktrace:
 at Object.createContext (/Users/thomas/myapp/node_modules/pixi-gl-core/src/createContext.js:20)
    at new WebGLRenderer (/Users/thomas/myapp/node_modules/pixi.js/lib/core/renderers/webGL/webGLRenderer.js:210)
    at PixiService.init (pixi.service.ts:106)
    at RendererComponent.ngOnInit (renderer.component.ts:38)

some people on linux and mac (like myself) have had their graphics cards blacklisted for webGL
https://github.com/electron/electron/issues/8217

i looked at the pixi.service.ts/js code in the angular2pixi package and change the line:
`this.renderer = new PIXI.WebGLRenderer(w, h, { transparent: true, autoResize: false, resolution: 1, view: el });`
to
`this.renderer = new PIXI.CanvasRenderer(w, h, { transparent: true, autoResize: false, resolution: 1, view: el });`

a nice fix would be to add some logic that checks if webgl is supported and if not calls CanvasRenderer instead

**Comment by Shadowstep33** [comment]
Excellent suggestion! I will implement this with the next patch and close this ticket when it's there 👍

**Comment by nphias** [comment]
<script type="text/javascript">
    var type = "WebGL"
    if(!PIXI.utils.isWebGLSupported()){
      type = "canvas"
    }

    PIXI.utils.sayHello(type)
  </script>

**Comment by Shadowstep33** [comment]
This is resolved in v 0.0.15 but forgot to put it in commit message
