### ISSUE TITLE
more detailed example needed... homeSceneReady does not appeared to get triggered

### ISSUE THREAD

**Issue by nphias** [Shadowstep33/Angular2Pixi#8]
myComponent.ts

```
export class myComponent {
    homeScene: any;
    constructor(){}
    homeSceneReady(scene: any){
        console.log("scene:"+ scene);
        this.homeScene = scene;
    }
}
```
myComponent.html

```
<renderer #renderer [width]="w" [height]="h">
	<home-scene
			[renderer]="renderer"
			(stageUpdated)="homeSceneReady($event)">
		<sprite
				[x]="w * 0.5"
				[y]="h * 0.6"
				imgUrl="./assets/img/background.jpg"
				*ngIf="homeScene"
				scale="1"
				[container]="homeScene.layers.hud"
		></sprite>
	</home-scene>
</renderer>
```
I dont get the console log for scene, i cant see my image for the sprite
and it complains about the home-scene tags not existing

help appreciated

**Comment by Shadowstep33** [comment]
My apologies, I was re-reading the readme and there's a big gap I left... home-scene is not an arbitrary tag, but is a custom component such that it has an output called stageUpdated that is an event emitter that is calling the function in the parent scope. 

```
@Component({
  selector: 'home-scene',
  templateUrl: './homeScene.html'
})
export class HomeSceneComponent extends GamePage {
  @Input() renderer: RendererComponent;
  @Output() stageUpdated = new EventEmitter();

  layers = {
	background: new PIXI.Container(),
	hud: new PIXI.Container(),
	extras: new PIXI.Container()
  };

	constructor(
		public scene: SceneService
	) {
	}

        ngOnInit(){
                this.scene.init(this.layers);


	//Add layers to homescene stage
	this.scene.mainStage.addChild(this.layers.background);
	this.scene.mainStage.addChild(this.layers.hud);
	this.scene.mainStage.addChild(this.layers.extras);


	        this.stageUpdated.emit(this.scene);
        }
```

Mine extends GamePage (another custom component) as there was some re-usable member variables and functions I needed, but this may not be the case for you. 

I will most likely be adding those ```mainStage.addChild(x)``` lines to the sceneService itself to make it easier for the user. Ideally, I want to create a SceneComponent that will essentially take the place of my GamePage component that is being extended. Let me know if that helps

**Comment by nphias** [comment]
ok.. with this code i have a new subcomponent like home-scene.. and the homeSceneReady is triggered in the parent component.  Great so far!  .. but what does your homeScene.html look like?.. it contains the @Input() renderer: RendererComponent; ?

**Comment by nphias** [comment]
I see how most things sequence together .. but i am unable to see the sprite .. does it need another call somewhere to render it?

**Comment by Shadowstep33** [comment]
At minimum you need a renderer and sprite component. Since yoi are using the scene component make sure your sprite component has the attribute container that is a reference to the mainStage of the scene or a created layer. I will work on creating a full bunny sprite plunkr example this weekend to make it easier.

**Comment by Shadowstep33** [comment]
My home scene is just passed a renderer. My sprite is passed a container that I add to the scene's layers by passing the layers via scene.init (homescene extends scene)

**Comment by Shadowstep33** [comment]
Arg, I'm mixing up the new build a bit! Homescene does not extend scene; please ignore that last comment. I will try to publish the new build tomorrow and some extra examples/docs if you dont mind waiting until then. Im about to be afk

**Comment by Shadowstep33** [comment]
But with the current build, homescene.html just has sprites in it that reference once of the layers. The tag for home-scene itself should be passed the renderer

**Comment by Shadowstep33** [comment]
I published v0.0.15 and made this example quickly in case you want to try more tonight. About to go now for real, hopefully this helps :) Make sure to update your angular2pixi!

**Comment by Shadowstep33** [comment]
I'm adding some information to the wiki and pushed v0.0.16 to npm and github. It should keep things a bit simpler/more out of the box - I realized I was adding the scene mainStage to renderer worldStage in my custom scene components. Now it's a part of the sceneComponent itself.

**Comment by Shadowstep33** [comment]
Sorry for the spam of replies but @nphias let me know if/when I can close this issue :) Weekends are my main time to work on personal projects such as A2P so I'm just hyper focused on it right now... haha

**Comment by nphias** [comment]
Hey @Shadowstep33 i just about got it working.. had to hack about ..but its good.. there is some redundant code in your wiki examples .. no idea what difference the @viewchild has .. i am still using the stageUpdated event to get back to my main..  would be nice to have a working bunny example in an examples directory.. keep up the good work my friend.. :)

**Comment by Shadowstep33** [comment]
@nphias working bunny in examples is my next goal :) May not happen till mid/end of this coming week thought. Just out of curiosity, what did you have to hack in a2p? And did you update to latest?

The @ViewChild is just so you can reference the RendererComponent from your page that it exists in since it is created via an element

**Comment by nphias** [comment]
as i remarked in https://github.com/Shadowstep33/Angular2Pixi/issues/6
the NPM package doesnt function like other NPM typescript modules
