### ISSUE TITLE
index.ts is missing from TypeScript compilation

### ISSUE THREAD

**Issue by GerkinDev** [Shadowstep33/Angular2Pixi#9]
Hi, I'm trying to use your package, but I got an error when `ng serve`:

> Module build failed: Error: /path/to/app/node_modules/angular2pixi/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

It asks me to open an issue, so do I.

* `@angular-devkit/core`: 0.0.28
* `@angular/cli`: 1.6.3
* `@angular/common`: 5.2.3
* `@angular/compiler-cli`: 5.1.2
* `@angular/core`: 5.2.3

**Comment by Shadowstep33** [comment]
Thank you very much @GerkinDev, I won't lie I was not aware of APF but I will standardize this package to use that! This will likely solve https://github.com/Shadowstep33/Angular2Pixi/issues/6 as well.

**Comment by GerkinDev** [comment]
If you allow me to do so, I'm working on a big PR with refactoring to lighten the package & clarify the structure. I got it to work with that on my Angular repo.
The fork is here: https://github.com/GerkinDev/Angular2Pixi
The Angular2 repo is here: https://github.com/GerkinDev/ithoughts.io-site
Once stable, I'll PR. It will come with README improvements

I would be pleased if you were able to provide me a tslint file configured with your coding standards

**Comment by Shadowstep33** [comment]
A standard tslint will do, I'm not picky :) I just did some initial refactoring, if I have time to test it before work I will. I'll take a look at your PR when it's ready because it will likely have extra stuff I'm not accounting for, I need to re-update myself with todays Angular and TS standards 😎

**Comment by Shadowstep33** [comment]
btw I'm glad to have another contributor on board, I eagerly await your PR

**Comment by Shadowstep33** [comment]
the latest is published to npm and pushed to git (v0.2.0). It seems to be working more smoothly for me in a new Angular project running latest angular and ts 2.4.2.

@nphias @Jeff-Clark-MST let me know if this fixes https://github.com/Shadowstep33/Angular2Pixi/issues/6 for you and I will close that ticket and this one.

@GerkinDev Please feel free to still make your PR, you likely will see some extra things to clean up. I think I copied the tsconfig from your fork.

**Comment by GerkinDev** [comment]
Hmm, some parts of your code are unclear and seems kinda obsolete. I refactor as much as I can, but you'll have to clean up what's left.

**Comment by Shadowstep33** [comment]
@GerkinDev the codebase in general or the recent commits?

**Comment by GerkinDev** [comment]
Issues like #10 . Working hard on it

**Comment by Shadowstep33** [comment]
Excellent :) @GerkinDev

**Comment by GerkinDev** [comment]
I'm almost done, just a little problem with AoT with `ng build --prod`. Without the `--prod` flag, it works well, but I've got a problem with the decorator.

**Comment by nphias** [comment]
guys any news on this working as a module?  ..   also a clean up of the code and better in-line comments for using this in a parent multi child component setup would be really helpful.. ( i am still a noob to both pixi and TS) ...  trying to work out how to use it effectively... if i have any enlightment / epiphany on it .. i will share of course.

**Comment by Shadowstep33** [comment]
> guys any news on this working as a package module

v 0.2.0 should work if you have the latest angular (5.2.4) and typescript (2.4.2). You may have to wrestle with dependencies if you are upgrading (for example, I'm using Ionic and I had to update ionic-angular@latest as I was on an older version... took me a good bit ;) )

> I guess I am also interested in the architecture of this framework.. why not just inject the application as a service.. like in this example

The overall architecture requires more thought and planning but as an initial impetus for development the goal was to abstract out the modules and functionality of pixi into Components for sake of easy transcribing and scene creation (via HTML). The goal was to also pre-package some of the core necessities for rendering and developing games so hybrid game code can be overall less WET and have more out of the box functionality. It's basically meant to be an entire game rendering framework, not just a service.

**Comment by Shadowstep33** [comment]
I am closing this ticket in the meantime as some architectural changes have been made that should have the package at least 'working'. Currently v0.3.0
